apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-app-deployment
  namespace: webrtc-app
  labels:
    app: webrtc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc-app
  template:
    metadata:
      labels:
        app: webrtc-app
    spec:
      containers:
      - name: webrtc-app
        image: rahuldev365/webrtc-app
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 10



