kind: Service
apiVersion: v1
metadata:
  name: webrtc-app-service
  namespace: webrtc-app
spec:
  selector:
    app: webrtc-app
  ports:
    - protocol: TCP  
      port: 3000
      targetPort: 3000
  type: ClusterIP
